language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOCKEN
  local_dir: react-web-components/build
  on:
    branch:
      - master
      - devel
